### ISSUE TITLE
Need read method for rapid.regression

### ISSUE THREAD

**Issue by mzed** [mzed/rapid#1]
The read method hasn't been implemented yet.

**Comment by ataut** [comment]
Hi Mike, any update on this? We're about to open up our [BBDMI repo](https://gitlab.huma-num.fr/bbdmi/bbdmi), and would like to move from rapidmax to rapid, and the Reading of models is the only thing that's holding us up.....  For the moment, Francesco has implemented a workaround, but reading/writing from a dict and training after the dictionary is loaded. Cheers. AT

**Comment by mzed** [comment]
I'll have a look at it this afternoon and see how close it could be.

**Comment by mzed** [comment]
Try v0.0.4 here: https://github.com/mzed/rapid/releases/tag/v0.0.4

Let me know if it works, and I'll close this. Or, if it fails...

**Comment by francesco-di-maggio** [comment]
Hi Michel, just tested it on my Intel / M1 machines, and it works like a charm. I like rapid outputs a bang now when a model is read. Well done. FDM

**Comment by mzed** [comment]
Great! I thought that bang would be helpful. It shouldn't bang if the read failed for some reason. I think this version still has the path problems of previous objects, but at least it's a step in the right direction.
